"""empty message

Revision ID: cb5aa085f1bf
Revises: be2b4c632002
Create Date: 2024-07-09 05:27:37.671494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5aa085f1bf'
down_revision = 'be2b4c632002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bag')
    op.drop_table('bag_product')
    with op.batch_alter_table('bag_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_product', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('image_url_product', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('price_product', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['name_product'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('bag_id')
        batch_op.drop_column('price')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bag_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('bag_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'bag', ['bag_id'], ['id'])
        batch_op.create_foreign_key(None, 'item', ['product_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('price_product')
        batch_op.drop_column('image_url_product')
        batch_op.drop_column('name_product')

    op.create_table('bag_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bag_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bag.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
